import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [answer, setAnswer] = useState(0)
  const [tradingFee, setTradingFee] = useState(0.001)
  const [mintFee, setMintFee] = useState(0.003)
  const [priceChange, setPriceChange]= useState(0.25)
  const [positionSize, setPositionSize] = useState(2)
  const [usdcUsedToMintVLP, setUsdcUsedToMintVLP] =  useState(5)
  const [totalUsdcInVault, setTotalUsdcInVault] =  useState(50)

  useEffect(()=>{
    calculate()
  },[tradingFee,mintFee,priceChange,positionSize,usdcUsedToMintVLP,totalUsdcInVault])
  
  const calculate = ()=>{
    const million = 10 ** 6;

    const priceChange_v = priceChange; // 25%
    const positionSize_v = positionSize * million;
    const usdcUsedToMintVLP_v = usdcUsedToMintVLP * million;
    const totalUsdcInVault_v = totalUsdcInVault * million;

    const profit =
      (priceChange_v * positionSize_v * usdcUsedToMintVLP_v) / (totalUsdcInVault_v + usdcUsedToMintVLP_v) -
      4 * tradingFee * positionSize_v-
      2 * mintFee * usdcUsedToMintVLP_v;

    setAnswer(profit)
  }

  return (
    <>
      <Head>
        <title>Simple App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-screen h-screen bg-black text-white'>
        <div className='flex flex-col items-center'>
          <div className='mt-20'></div>
          <div className='grid w-[500px] gap-2 grid-cols-2 p-6 border-[#C1C1C1] rounded-2xl border'>
            <div>trading fee</div>
            <input className='text-black p-1' value={tradingFee} onChange={(e)=>{
              setTradingFee(e.target.value)
            }}
              type= "number"
            ></input>
            
            <div>mint fee</div>
            <input className='text-black p-1' type= "number" value={mintFee}
              onChange={(e)=>{
                setMintFee(e.target.value)
              }}
            ></input>
            
            <div>price change</div>
            <input className='text-black p-1'value={priceChange}
              onChange={(e)=>{
                setPriceChange(e.target.value)
              }}
              type="number"
            ></input>

            <div>position size</div>
            <input className='text-black p-1' value={positionSize}
              onChange={(e)=>{
                setPositionSize(e.target.value)
                console.log(e.value)
              }}
              type="number"
            ></input>

            <div>udsc used to mint</div>
            <input className='text-black p-1' value={usdcUsedToMintVLP} 
              onChange={(e)=>{
                setUsdcUsedToMintVLP(e.target.value)
              }}
              type="number"
            ></input>

            <div>total usdc in vault</div>
            <input className='text-black p-1' value={totalUsdcInVault} 
              onChange={(e)=>{
                setTotalUsdcInVault(e.target.value)
              }}
              type="number"
            ></input>
            
            <div className='flex gap-2'>
              <div>Profit :</div>
              <div className='text-green-500'>{answer}</div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
